# Generated by Django 2.2.5 on 2019-09-27 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190927_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 19, 21, 4, 15740, tzinfo=utc)),
        ),
    ]
