# Generated by Django 2.2.5 on 2019-09-28 01:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190928_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 1, 19, 29, 901295, tzinfo=utc)),
        ),
    ]
